# we recommend to read config_details.yaml first.


data:
  # data_path: '/home/hxyang/LightningDiT/jgw_data/latent/vavae_f16d32/train_128'
  source_data_path: path/lantent/source/
  target_data_path: path/lantent/target/
  fid_reference_file:  # <---- path to your fid_reference_file.npz. download it from ADM

  # recommend to use default settings
  image_size: 128
  num_classes: 1
  num_workers: 8
  latent_norm: true
  latent_multiplier: 1.0

# recommend to use default settings (we wil release codes with SD-VAE later)
vae:
  model_name: 'vavae_f16d32'
  downsample_ratio: 16

# recommend to use default settings
model:
  model_type: LightningDiT-XL/1
  use_qknorm: false
  use_swiglu: true
  use_rope: true
  use_rmsnorm: true
  wo_shift: false
  in_chans: 32

# recommend to use default settings
train:
  # weight_init: /home/hxyang/LightningDiT/output/lightningdit_xl_vavae_f16d32/checkpoints/0020000.pt
  max_steps: 100000
  global_batch_size: 256
  global_seed: 0
  output_dir: 'output'
  exp_name: 'lightningdit_xl_vavae_f16d32' # <---- experiment name, set as you like
  ckpt: null
  log_every: 100
  ckpt_every: 5000
optimizer:
  lr: 0.0002
  beta2: 0.95
  
# recommend to use default settings
transport:
  path_type: Linear
  prediction: velocity
  loss_weight: null
  sample_eps: null
  train_eps: null
  use_cosine_loss: true
  use_lognorm: true

# recommend to use default settings
sample:
  mode: ODE
  sampling_method: euler
  atol: 0.000001
  rtol: 0.001
  reverse: false
  likelihood: false
  num_sampling_steps: 250
  cfg_scale: 10.0 # <---- cfg scale, for 800 epoch performance with FID=1.35 cfg_scale=6.7
                  #       for 64 epoch performance with FID=2.11 cfg_scale=10.0
                  #       you may find we use a large cfg_scale, this is because of 2 reasons:
                  #       we find a high-dimensional latent space requires a large cfg_scale to get good performance than f8d4 SD-VAE
                  #       we enable cfg interval, which reduces the negative effects of large cfg on high-noise parts. This means larger cfg can be utilized
  
  # recommend to use default settings
  per_proc_batch_size: 4
  fid_num: 50000
  cfg_interval_start: 0.11
  timestep_shift: 0.3